apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: psychology-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth-service:latest
          ports:
            - containerPort: 50051
          env:
            - name: AUTH_GRPC_PORT
              value: '50051'
            - name: JWT_SECRET
              value: 'test-secret'
            - name: AUTH_DB_URL
              value: 'postgres://user:pass@db-service.psychology-app.svc.cluster.local:5432/authdb'
          readinessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: 50051
            initialDelaySeconds: 15
            periodSeconds: 20
