apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: psychology-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth
          image: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:staging-latest
          ports:
            - containerPort: 50051
          env:
            - name: AUTH_GRPC_PORT
              value: '50051'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: jwt-secret
            - name: AUTH_DB_URL
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: auth-db-url
          resources:
            limits:
              memory: '128Mi'
              cpu: '100m'
      imagePullSecrets:
        - name: dockerhub-creds
