apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
  namespace: psychology-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          env:
            - name: POSTGRES_DB
              value: authdb
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: pass
          ports:
            - containerPort: 5432
          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - exec pg_isready -U user -d authdb
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: psychology-app
spec:
  selector:
    app: db-service
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
