name: Auth Service CI/CD

on:
  push:
    branches: [psychology-migration]
    paths:
      - 'microservices/auth-service/**'
  pull_request:
    branches: ['psychology-migration']

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build
        working-directory: microservices/auth-service
        run: go build -v ./...

      - name: Run unit tests
        working-directory: microservices/auth-service
        run: go test -v -coverprofile=coverage.out -short ./...

      - name: Run integration tests
        working-directory: microservices/auth-service
        run: go test -v -tags=integration ./...
        env:
          AUTH_DB_URL: 'postgres://test:test@localhost:5432/testdb?sslmode=disable'
          REDIS_URL: 'redis://localhost:6379/0'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: microservices/auth-service/coverage.out

  deploy-staging:
    needs: build-test
    if: github.ref == 'refs/heads/psychology-migration'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        working-directory: microservices/auth-service
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:${{ github.sha }}

      - name: Deploy to Kubernetes
        uses: steebchen/kubectl@v2.0.0
        with:
          command: apply -f kubernetes/
          kubectl-version: v1.25.0
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA_STAGING }}
          IMAGE_TAG: ${{ github.sha }}
